<?php
return [
    'agregado' => [
        'tabela' => 'Agregado Familiar',
        'campos' => [
            'ID' => 'ID Interno Agregado',
            'NumProcesso' => 'Número do Processo',
            'Nome' => 'Nome do Elemento do Agregado',
            'Parentesco' => 'Parentesco',
            'Sexo' => 'Sexo',
            'DataNasc' => 'Data de Nascimento',
            'NumCC' => 'Número do Cartão de Cidadão',
            'NumContribuinte' => 'Número de Contribuinte',
            'EstadoCivil' => 'Estado Civil',
            'Passaporte' => 'Passaporte',
            'Titulo' => 'Título de Residência',
            'Idade' => 'Idade',
            'Obs' => 'Observações',
        ],
    ],
    'arquivados_reabertos' => [
        'tabela' => 'Histórico dos Processos Arquivados e Reabertos',
        'campos' => [
            'ID' => 'ID Interno da Arquivação/Reabertura',
            'NumProcesso' => 'Número do Processo',
            'DataArquivacao' => 'Data de Arquivação',
            'MotivoArquivacao' => 'Motivo do Arquivamento',
            'DataReabertura' => 'Data da Reabertura',
            'UtilizadorArquiva' => 'Utilizador que Arquivou',
            'UtilizadorReabre' => 'Utilizador que Reabriu',
        ],
    ],
    'atendimentos' => [
        'tabela' => 'Atendimentos',
        'campos' => [
            'ID' => 'ID Interno do Atendimento',
            'NumProcesso' => 'Número do Processo',
            'Data' => 'Data do Atendimento',
            'Tipo' => 'Tipo do Atendimento',
            'Situacao' => 'Descrição do Atendimento',
            'Encaminhamento' => 'Encaminhamento',
            'Nome' => 'Nome do Técnico',
            'inssocial' => 'É acompanhado/a por instituição social? (Sim/Não)',
            'Obsinssocial' => 'Observações - Instituição social',
            'hsmuni' => 'Está inscrito em HS noutro município? (Sim/Não)',
            'Obshsmuni' => 'Observações - Inscrito em HS noutro município',
            'doencas' => 'Tem doenças crónicas? (Sim/Não)',
            'Obsdoencas' => 'Observações - Doença',
            'incapacidade' => 'Tem atestado de incapacidade multiusos? (Sim/Não)',
            'Obsincapacidade' => 'Observações - Incapacidade',
            'reside' => 'Reside em São João da Madeira? (Sim/Não)',
            'Obsreside' => 'Observações - Residência',
            'work' => 'Trabalha em São João da Madeira?',
            'Obswork' => 'Observações - Trabalho',
            'study' => 'Estuda em São João da Madeira?',
            'Obsstudy' => 'Observações - Estudos',
            'viole' => 'É/considera-se vítima de violência doméstica? (Sim/Não)',
            'Obsviole' => 'Observações - Violência Doméstica',
            'estaviole' => 'Tem estatuto de vítima? (Sim/Não)',
            'Obsestaviole' => 'Observações - Estatuto de Vítima',
            'relacio' => 'Mantém relacionamento amoroso? (Sim/Não)',
            'Obsrelacio' => 'Observações - Relacionamento Amoroso',
            'desem' => 'Está Desempregado? (Sim/Não)',
            'Obsdesem' => 'Observações - Desemprego',
            'motivo' => 'Motivo da Candidatura',
            'obsmotivo' => 'Observações - Motivo da Candidatura',
            'apoio' => 'Beneficia de algum apoio ao arrendamento (Porta 65/ASA/Medidas Mais Habitação)? (Sim/Não)',
            'Obsapoio' => 'Observações - Apoio',
        ],
    ],
    'copialimpeza' => [
        'tabela' => 'Cópia dos Registos de limpeza das validações dos processos',
        'campos' => [
            'ID' => 'ID Interno da Validação',
            'NumProcesso' => 'Número do Processo',
            'DataValidacao' => 'Data de Validação',
            'EstadoAntigo' => 'Estado Antigo',
            'EstadoNovo' => 'Estado Novo',
            'UtilizadorValida' => 'Utilizador que Validou',
        ],
    ],
    'ficheiros' => [
        'tabela' => 'Ficheiros',
        'campos' => [
            'ID' => 'ID Interno do Ficheiro',
            'NumProcesso' => 'Número do Processo',
            'NomeFicheiro' => 'Nome do Ficheiro',
            'Descricao' => 'Descrição do Ficheiro',
            'Utilizador' => 'Utilizador que fez o Upload',
            'Pasta' => 'Pasta',
            'Data' => 'Data de Submissão',
            'Extensao' => 'Extensão do Ficheiro',
        ],
    ],
    'logs_sistema' => [
        'tabela' => 'Registo de Logs do Sistema',
        'campos' => [
            'id' => 'ID Interno',
            'tabela' => 'Tabela',
            'id_registo' => 'ID do Registo',
            'acao' => 'Ação Realizada',
            'coluna' => 'Coluna Alterada',
            'valor_antigo' => 'Valor Antigo',
            'valor_novo' => 'Valor Novo',
            'utilizador' => 'Utilizador',
            'data_log' => 'Data do Registo',
        ],
    ],
    'matriz' => [
        'tabela' => 'Matriz de Ponderação',
        'campos' => [
            'ID' => 'ID Interno da Matriz',
            'NumProcesso' => 'Número do Processo',
            'TipoAlojamento' => 'Tipo de Alojamento',
            'TotalTipoAlojamento' => 'Total Ponderação para o Tipo de Alojamento',
            'RegimeAlojamento' => 'Regime de Alojamento',
            'TotalRegimeAlojamento' => 'Total Ponderação para o Regime de Alojamento',
            'Motivo' => 'Motivo',
            'TotalMotivo' => 'Total Ponderação para o Motivo',
            'TempoResidencia' => 'Tempo de Residência',
            'TotalTempoResidência' => 'Total Ponderação para o Tempo de Residência',
            'Incapacidade' => 'Incapacidade',
            'TotalIncapacidade' => 'Total Ponderação para a Incapacidade',
            'AnosIdade' => 'Anos de Idade',
            'TotalAnosIdade' => 'Total Ponderação para a Idade',
            'Violencia' => 'Violência',
            'TotalViolencia' => 'Total Ponderação para a Violência',
            'TipoFamilia' => 'Tipo de Família',
            'TotalTipoFamilia' => 'Total Ponderação para o Tipo de Família',
            'SituacaoLaboral' => 'Situação Laboral',
            'TotalSituacaoLaboral' => 'Total Ponderação para a Situação Laboral',
            'IAS' => 'IAS',
            'TotalIAS' => 'Total Ponderação para o IAS',
            'TotalFinal' => 'Classificação Total Final',
            'Data' => 'Data de Criação',
            'Ativo' => 'Estado (Ativo/Inativo)',
            'Utilizador' => 'Utilizador',
        ],
    ],
    'nova_matriz' => [
        'tabela' => 'Nova Matriz de Classificação',
        'campos' => [
            'ID' => 'ID Interno',
            'NumProcesso' => 'Número do Processo',
            'Data' => 'Data da Matriz',
            'NumElementos' => 'Número de Elementos do Agregado',
            'RendimentoMensal' => 'Rendimento Mensal',
            'ValorIAS' => 'Valor IAS',
            'ClassifValorIAS' => 'Classificação - Valor IAS',
            'NumFilhos' => 'Número de Filhos',
            'ClassifNumFilhos' => 'Classificação - Número de Filhos',
            'Incapacidade' => 'Incapacidade (%)',
            'ClassifIncapacidade' => 'Classificação - Incapacidade',
            'Idade' => 'Idade do Requerente',
            'ClassifIdade' => 'Classificação - Idade',
            'Monoparental' => 'Família Monoparental',
            'ClassifMonoparental' => 'Classificação - Monoparentalidade',
            'Violenca' => 'Vítima de Violência',
            'ClassifViolencia' => 'Classificação - Violência',
            'Alojamento' => 'Condições de Alojamento',
            'ClassifAlojamento' => 'Classificação - Alojamento',
            'Hab1' => 'Fator Habitação 1',
            'ClassifHab1' => 'Classificação - Fator Habitação 1',
            'Hab2' => 'Fator Habitação 2',
            'ClassifHab2' => 'Classificação - Fator Habitação 2',
            'Hab3' => 'Fator Habitação 3',
            'ClassifHab3' => 'Classificação - Fator Habitação 3',
            'Concelho' => 'Residência no Concelho',
            'ClassifConcelho' => 'Classificação - Concelho',
            'Renda' => 'Valor da Renda',
            'ClassifRenda' => 'Classificação - Renda',
            'ValorMatriz' => 'Valor Total da Matriz',
            'Ativo' => 'Matriz Ativa',
            'Utilizador' => 'Utilizador',
        ],
    ],
    'pais' => [
        'tabela' => 'Países',
        'campos' => [
            'paisId' => 'ID do País',
            'paisNome' => 'Nome do País (PT)',
            'paisName' => 'Nome do País (EN)',
        ],
    ],
    'percapita' => [
        'tabela' => 'Rendimento Per Capita',
        'campos' => [
            'ID' => 'ID Interno',
            'NumProcesso' => 'Número do Processo',
            'TipoRendimento' => 'Tipo de Rendimento 1',
            'ValorRendimento' => 'Valor do Rendimento 1',
            'TipoRendimento2' => 'Tipo de Rendimento 2',
            'ValorRendimento2' => 'Valor do Rendimento 2',
            'TipoRendimento3' => 'Tipo de Rendimento 3',
            'ValorRendimento3' => 'Valor do Rendimento 3',
            'TipoRendimento4' => 'Tipo de Rendimento 4',
            'ValorRendimento4' => 'Valor do Rendimento 4',
            'TipoRendimento5' => 'Tipo de Rendimento 5',
            'ValorRendimento5' => 'Valor do Rendimento 5',
            'TipoRendimento6' => 'Tipo de Rendimento 6',
            'ValorRendimento6' => 'Valor do Rendimento 6',
            'TipoRendimento7' => 'Tipo de Rendimento 7',
            'ValorRendimento7' => 'Valor do Rendimento 7',
            'TipoRendimento8' => 'Tipo de Rendimento 8',
            'ValorRendimento8' => 'Valor do Rendimento 8',
            'TipoRendimento9' => 'Tipo de Rendimento 9',
            'ValorRendimento9' => 'Valor do Rendimento 9',
            'TipoRendimento10' => 'Tipo de Rendimento 10',
            'ValorRendimento10' => 'Valor do Rendimento 10',
            'TipoRendimento11' => 'Tipo de Rendimento 11',
            'ValorRendimento11' => 'Valor do Rendimento 11',
            'TipoRendimento12' => 'Tipo de Rendimento 12',
            'ValorRendimento12' => 'Valor do Rendimento 12',
            'TotalRendimento' => 'Total de Rendimentos',
            'TipoDespesa' => 'Tipo de Despesa',
            'TipoDivida' => 'Tipo de Dívida',
            'ValorDespesa' => 'Valor da Despesa',
            'ValorDivida' => 'Valor da Dívida',
            'Elementos' => 'Número de Elementos',
            'Data' => 'Data do Cálculo',
            'ValorPerCapita' => 'Valor Final Per Capita',
            'Ativo' => 'Estado (Ativo/Inativo)',
            'Utilizador' => 'Utilizador que Registou',
        ],
    ],
    'pessoas' => [
        'tabela' => 'Registo de Pessoas',
        'campos' => [
            'NumProcesso' => 'Número do Processo',
            'Nome' => 'Nome Completo',
            'DataNasc' => 'Data de Nascimento',
            'Idade' => 'Idade',
            'Sexo' => 'Sexo',
            'EstadoCivil' => 'Estado Civil',
            'Nacionalidade' => 'Nacionalidade',
            'NumCC' => 'Número do Cartão de Cidadão',
            'Validade' => 'Validade do Documento',
            'NumContribuinte' => 'NIF (Número de Contribuinte)',
            'NumSegSocial' => 'NISS (Número de Segurança Social)',
            'Passaporte' => 'Número de Passaporte',
            'TituloResidencia' => 'Título de Residência',
            'Morada' => 'Morada Completa',
            'Contacto' => 'Contacto Telefónico principal',
            'OutrosContactos' => 'Contactos Alternativos',
            'Email' => 'Endereço de Email',
        ],
    ],
    'ponderacoes' => [
        'tabela' => 'Ponderações do Sistema',
        'campos' => [
            'ID' => 'ID Interno',
            'Variavel' => 'Nome da Variável',
            'Ponderacao' => 'Valor da Ponderação',
        ],
    ],
    'processo' => [
        'tabela' => 'Processos Gerais',
        'campos' => [
            'ID' => 'ID Interno',
            'NumProcesso' => 'Número do Processo',
            'NIPG' => 'NIPG (Núm. de Identificação de Processo Geral)',
            'NumElementos' => 'Número de Elementos',
            'TipoFamilia' => 'Tipologia Familiar',
            'TipoHab' => 'Tipo de Habitação Necessária',
            'Reabertura' => 'Processo Reaberto',
            'ValorPer' => 'Valor Per Capita',
            'Resultado' => 'Resultado da Avaliação',
            'ResultadoNovo' => 'Novo Resultado da Avaliação',
            'Info' => 'Informação Adicional',
            'DocNecessarios' => 'Documentos Necessários em falta',
            'Estado' => 'Estado do Processo',
            'Validado' => 'Processo Validado?',
            'DataArquivado' => 'Data de Arquivamento',
            'MotivoArquivado' => 'Motivo de Arquivamento',
            'Obs' => 'Observações do Processo',
            'Concelho' => 'Concelho de Referência',
            'Partilha' => 'Partilha de Informação',
        ],
    ],
    'registo_ativos' => [
        'tabela' => 'Registo de Processos Ativos',
        'campos' => [
            'ID' => 'ID Interno',
            'Ano' => 'Ano de Referência',
            'Data' => 'Data do Registo',
            'Ativos' => 'Quantidade de Ativos',
        ],
    ],
    'registolimpeza' => [
        'tabela' => 'Histórico de Limpezas de Sistema',
        'campos' => [
            'ID' => 'ID da Limpeza',
            'Data' => 'Data de Execução',
            'User' => 'Utilizador que Executou',
        ],
    ],
    'tipologia' => [
        'tabela' => 'Tipologias Habitacionais',
        'campos' => [
            'IDPonderacoes' => 'ID da Ponderação Associada',
            'Tipologia' => 'Nome da Tipologia (ex: T1, T2)',
            'Pontos' => 'Pontos Atribuídos',
        ],
    ],
    'utilizadores' => [
        'tabela' => 'Gestão de Utilizadores',
        'campos' => [
            'ID' => 'ID Interno',
            'Nome' => 'Nome do Utilizador',
            'Email' => 'Endereço de Email',
            'Password' => 'Palavra-passe',
            'Tipo' => 'Tipo de Acesso (Perfil)',
            'Ativo' => 'Conta Ativa',
        ],
    ],
    'validaprocesso' => [
        'tabela' => 'Validação de Processos',
        'campos' => [
            'ID' => 'ID Interno da Validação',
            'NumProcesso' => 'Número do Processo',
            'DataValidacao' => 'Data de Validação',
            'EstadoAntigo' => 'Estado Antigo',
            'EstadoNovo' => 'Estado Novo',
            'UtilizadorValida' => 'Utilizador que Validou',
        ],
    ],
    'valores' => [
        'tabela' => 'Valores de Referência',
        'campos' => [
            'ID' => 'ID Interno',
            'ValorIAS' => 'Valor do IAS em vigor',
            'ValorRSI' => 'Valor do RSI em vigor',
        ],
    ],
];
?>
